@BlogAppApiHostAddress = http://localhost:5267

### USERS: get all
GET {{BlogAppApiHostAddress}}/api/users
Accept: application/json

### USERS: create
POST {{BlogAppApiHostAddress}}/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "api_tester",
  "age": 25,
  "fullName": "API Tester",
  "role": 1
}

> {%
  client.global.set("userId", response.body.id);
%}

### USERS: get by id
GET {{BlogAppApiHostAddress}}/api/users/{{userId}}
Accept: application/json

### USERS: update
PUT {{BlogAppApiHostAddress}}/api/users/{{userId}}
Content-Type: application/json
Accept: application/json

{
  "userName": "api_tester_updated",
  "age": 26,
  "fullName": "API Tester Updated",
  "role": 2
}

### POSTS: get all
GET {{BlogAppApiHostAddress}}/api/posts
Accept: application/json

### POSTS: create
POST {{BlogAppApiHostAddress}}/api/posts
Content-Type: application/json
Accept: application/json

{
  "title": "HTTP Client Test Post",
  "description": "Created from BlogApp.API.http",
  "userId": "{{userId}}"
}

> {%
  client.global.set("postId", response.body.id);
%}

### POSTS: get by id
GET {{BlogAppApiHostAddress}}/api/posts/{{postId}}
Accept: application/json

### POSTS: update
PUT {{BlogAppApiHostAddress}}/api/posts/{{postId}}
Content-Type: application/json
Accept: application/json

{
  "title": "HTTP Client Test Post Updated",
  "description": "Updated from BlogApp.API.http",
  "userId": "{{userId}}"
}

### COMMENTS: get all
GET {{BlogAppApiHostAddress}}/api/comments
Accept: application/json

### COMMENTS: create
POST {{BlogAppApiHostAddress}}/api/comments
Content-Type: application/json
Accept: application/json

{
  "description": "Test comment from HTTP client",
  "userId": "{{userId}}",
  "postId": "{{postId}}",
  "parentId": null
}

> {%
  client.global.set("commentId", response.body.id);
%}

### COMMENTS: get by id
GET {{BlogAppApiHostAddress}}/api/comments/{{commentId}}
Accept: application/json

### COMMENTS: update
PUT {{BlogAppApiHostAddress}}/api/comments/{{commentId}}
Content-Type: application/json
Accept: application/json

{
  "description": "Test comment updated from HTTP client",
  "userId": "{{userId}}",
  "postId": "{{postId}}",
  "parentId": null
}

### COMMENTS: delete
DELETE {{BlogAppApiHostAddress}}/api/comments/{{commentId}}

### POSTS: delete
DELETE {{BlogAppApiHostAddress}}/api/posts/{{postId}}

### USERS: delete
DELETE {{BlogAppApiHostAddress}}/api/users/{{userId}}

### USERS: update with docker
PUT http://localhost:8080/api/users/4d524e30-9996-4dae-8c40-cf5c793e8fe8
Content-Type: application/json
Accept: application/json

{
  "userName": "api_tester_updated",
  "age": 26,
  "fullName": "API Tester Updated",
  "role": 2
}

### USERS: create user with post
POST {{BlogAppApiHostAddress}}/api/users/with-post
Content-Type: application/json
Accept: application/json

{
  "User": {
    "userName": "Cito_hotite",
    "age": 25,
    "fullName": "API Tester",
    "role": 1
    },
  
  "Post": {
      "title": "HTTP Client Test Post",
      "description": "Created from BlogApp.API.http"
    }
  }
